### ISSUE TITLE
Advance Search results - just spinning (as of 11/4/19)

### ISSUE THREAD

**Issue by cvntstscrty1** [xh4zr/caveon-core#11]
I thought it was due to a specific filter but looks like Analytics page not working at all.

My original message: I'm trying to fun a filter for specific Statuses in a client hub.  After selecting the parameters, it returns results but when I click on Analytics for that set it's just spins.  I've closed browser and reopened and ran it again and still spinning.
![Screen Shot 2019-11-04 at 2 17 24 PM](https://user-images.githubusercontent.com/51721430/68163053-6f184f80-ff0e-11e9-9fa9-659de1d3c828.png)

**Comment by xh4zr** [comment]
fixed. page now loads.
